#!/bin/bash

rm -rf .tmp
mkdir .tmp
browserify index.js > .tmp/bundle.js
uglifyjs .tmp/bundle.js -c -m > .tmp/bundle.min.js

cat > www/xgpush.js << EOL
`cat .tmp/bundle.min.js`
var XGPush = window._XGPush;
delete window._XGPush;
module.exports = new XGPush(require('cordova/exec'));
EOL
